-- 코드를 입력하세요

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND LAST_DAY('2022-10-01')
GROUP BY MONTH(START_DATE), CAR_ID
HAVING CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE  START_DATE BETWEEN '2022-08-01' AND LAST_DAY('2022-10-01')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
ORDER BY MONTH, CAR_ID DESC

